import logging
from importlib.metadata import version

from s2_sdk._append_session import AppendSession, BatchSubmitTicket
from s2_sdk._batching import append_inputs, append_record_batches
from s2_sdk._exceptions import (
    AppendConditionError,
    FencingTokenMismatchError,
    ReadUnwrittenError,
    S2ClientError,
    S2Error,
    S2ServerError,
    SeqNumMismatchError,
)
from s2_sdk._ops import S2, S2Basin, S2Stream
from s2_sdk._producer import Producer, RecordSubmitTicket
from s2_sdk._types import (
    AccessTokenInfo,
    AccessTokenScope,
    AccountMetricSet,
    Accumulation,
    AppendAck,
    AppendInput,
    AppendRetryPolicy,
    BasinConfig,
    BasinInfo,
    BasinMetricSet,
    BasinScope,
    Batching,
    CommandRecord,
    Compression,
    EncryptionAlgorithm,
    EncryptionKey,
    Endpoints,
    ExactMatch,
    Gauge,
    IndexedAppendAck,
    Label,
    MetricUnit,
    Operation,
    OperationGroupPermissions,
    Page,
    Permission,
    PrefixMatch,
    ReadBatch,
    ReadLimit,
    Record,
    Retry,
    Scalar,
    SeqNum,
    SequencedRecord,
    StorageClass,
    StreamConfig,
    StreamInfo,
    StreamMetricSet,
    StreamPosition,
    TailOffset,
    Timeout,
    TimeseriesInterval,
    Timestamp,
    Timestamping,
    TimestampingMode,
    metered_bytes,
)

__version__ = version("s2-sdk")

logging.getLogger(__name__).addHandler(logging.NullHandler())

__all__ = [
    "S2",
    "S2Basin",
    "S2Stream",
    "AppendSession",
    "BatchSubmitTicket",
    "Producer",
    "RecordSubmitTicket",
    "append_record_batches",
    "append_inputs",
    "Retry",
    "Timeout",
    "Compression",
    "AppendRetryPolicy",
    "Batching",
    "Endpoints",
    "Record",
    "AppendInput",
    "AppendAck",
    "EncryptionAlgorithm",
    "EncryptionKey",
    "IndexedAppendAck",
    "StreamPosition",
    "SeqNum",
    "Timestamp",
    "TailOffset",
    "ReadBatch",
    "ReadLimit",
    "SequencedRecord",
    "Page",
    "CommandRecord",
    "metered_bytes",
    "StorageClass",
    "TimestampingMode",
    "Timestamping",
    "StreamConfig",
    "BasinConfig",
    "BasinInfo",
    "BasinScope",
    "StreamInfo",
    "ExactMatch",
    "PrefixMatch",
    "Permission",
    "Operation",
    "OperationGroupPermissions",
    "AccessTokenScope",
    "AccessTokenInfo",
    "MetricUnit",
    "TimeseriesInterval",
    "AccountMetricSet",
    "BasinMetricSet",
    "StreamMetricSet",
    "Scalar",
    "Accumulation",
    "Gauge",
    "Label",
    "S2Error",
    "S2ClientError",
    "S2ServerError",
    "AppendConditionError",
    "FencingTokenMismatchError",
    "SeqNumMismatchError",
    "ReadUnwrittenError",
]
